"""add indexes for improved performance

Revision ID: f437b4507935
Revises: 236318ee3d3e
Create Date: 2017-08-19 09:20:59.084226

"""

# revision identifiers, used by Alembic.
revision = 'f437b4507935'
down_revision = '236318ee3d3e'

from alembic import op
import sqlalchemy as sa
import doorman.database


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_distributed_query_result_query_id', 'distributed_query_result', ['distributed_query_id', 'id'], unique=False)
    op.create_index('idx_distributed_query_result_query_task_id', 'distributed_query_result', ['distributed_query_id', 'distributed_query_task_id'], unique=False)
    op.create_index('idx_distributed_query_result_task_id', 'distributed_query_result', ['distributed_query_task_id', 'id'], unique=False)
    op.create_index('idx_distributed_query_task_node_id', 'distributed_query_task', ['node_id', 'id'], unique=False)
    op.create_index('idx_distributed_query_task_query_id', 'distributed_query_task', ['distributed_query_id', 'id'], unique=False)
    op.create_index('idx_distributed_query_task_status', 'distributed_query_task', ['status', 'id'], unique=False)
    op.create_index('idx_result_log_node_id', 'result_log', ['node_id', 'id'], unique=False)
    op.create_index('idx_result_log_timestamp_desc', 'result_log', [sa.text(u'timestamp DESC'), 'id'], unique=False)
    op.create_index('idx_status_log_node_id', 'status_log', ['node_id', 'id'], unique=False)
    op.create_index('idx_status_log_timestamp_desc', 'status_log', [sa.text(u'created DESC'), 'id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status_log_timestamp_desc', table_name='status_log')
    op.drop_index('idx_status_log_node_id', table_name='status_log')
    op.drop_index('idx_result_log_timestamp_desc', table_name='result_log')
    op.drop_index('idx_result_log_node_id', table_name='result_log')
    op.drop_index('idx_distributed_query_task_status', table_name='distributed_query_task')
    op.drop_index('idx_distributed_query_task_query_id', table_name='distributed_query_task')
    op.drop_index('idx_distributed_query_task_node_id', table_name='distributed_query_task')
    op.drop_index('idx_distributed_query_result_task_id', table_name='distributed_query_result')
    op.drop_index('idx_distributed_query_result_query_task_id', table_name='distributed_query_result')
    op.drop_index('idx_distributed_query_result_query_id', table_name='distributed_query_result')
    ### end Alembic commands ###
